name: clear_mamba_env
channels:
- bioconda
- conda-forge
- pkgs/main
- pkgs/r
dependencies:
- _libgcc_mutex=0.1=conda_forge
- _openmp_mutex=4.5=2_gnu
- _r-mutex=1.0.0=anacondar_1
- aom=3.12.1=h7934f7d_0
- argcomplete=3.6.2=py311h06a4308_0
- asttokens=3.0.0=py311h06a4308_0
- binutils_impl_linux-64=2.40=h5293946_0
- binutils_linux-64=2.40.0=hc2dff05_2
- bioconductor-annotate=1.80.0=r43hdfd78af_0
- bioconductor-annotationdbi=1.64.1=r43hdfd78af_0
- bioconductor-annotationhub=3.10.0=r43hdfd78af_0
- bioconductor-apeglm=1.24.0=r43hf17093f_1
- bioconductor-biobase=2.62.0=r43ha9d7317_3
- bioconductor-biocfilecache=2.10.1=r43hdfd78af_0
- bioconductor-biocgenerics=0.48.1=r43hdfd78af_2
- bioconductor-biocparallel=1.36.0=r43hf17093f_2
- bioconductor-biocversion=3.18.1=r43hdfd78af_0
- bioconductor-biostrings=2.70.1=r43ha9d7317_2
- bioconductor-clusterprofiler=4.10.0=r43hdfd78af_0
- bioconductor-data-packages=20250625=hdfd78af_0
- bioconductor-delayedarray=0.28.0=r43ha9d7317_2
- bioconductor-deseq2=1.42.0=r43hf17093f_2
- bioconductor-dose=3.28.1=r43hdfd78af_0
- bioconductor-edger=4.0.16=r43hf17093f_1
- bioconductor-enrichmentbrowser=2.32.0=r43hdfd78af_0
- bioconductor-enrichplot=1.22.0=r43hdfd78af_0
- bioconductor-experimenthub=2.10.0=r43hdfd78af_0
- bioconductor-fgsea=1.28.0=r43hf17093f_1
- bioconductor-genomeinfodb=1.38.1=r43hdfd78af_1
- bioconductor-genomeinfodbdata=1.2.11=r43hdfd78af_1
- bioconductor-genomicranges=1.54.1=r43ha9d7317_2
- bioconductor-ggtree=3.10.0=r43hdfd78af_0
- bioconductor-go.db=3.18.0=r43hdfd78af_0
- bioconductor-gosemsim=2.28.0=r43hf17093f_1
- bioconductor-graph=1.80.0=r43ha9d7317_1
- bioconductor-graphite=1.48.0=r43hdfd78af_0
- bioconductor-gseabase=1.64.0=r43hdfd78af_0
- bioconductor-gseabenchmarker=1.22.0=r43hdfd78af_0
- bioconductor-hdo.db=0.99.1=r43hdfd78af_2
- bioconductor-hgu133a.db=3.13.0=r43hdfd78af_4
- bioconductor-hgu133plus2.db=3.13.0=r43hdfd78af_4
- bioconductor-interactivedisplaybase=1.40.0=r43hdfd78af_0
- bioconductor-iranges=2.36.0=r43ha9d7317_2
- bioconductor-keggandmetacoredzpathwaysgeo=1.22.0=r43hdfd78af_0
- bioconductor-keggdzpathwaysgeo=1.40.0=r43hdfd78af_0
- bioconductor-kegggraph=1.62.0=r43hdfd78af_0
- bioconductor-keggrest=1.42.0=r43hdfd78af_0
- bioconductor-limma=3.58.1=r43ha9d7317_1
- bioconductor-matrixgenerics=1.14.0=r43hdfd78af_3
- bioconductor-mgsa=1.50.0=r43ha9d7317_2
- bioconductor-org.ag.eg.db=3.18.0=r43hdfd78af_0
- bioconductor-org.hs.eg.db=3.18.0=r43hdfd78af_0
- bioconductor-pathview=1.42.0=r43hdfd78af_0
- bioconductor-qvalue=2.34.0=r43hdfd78af_0
- bioconductor-rgraphviz=2.46.0=r43hf17093f_1
- bioconductor-s4arrays=1.2.0=r43ha9d7317_2
- bioconductor-s4vectors=0.40.2=r43ha9d7317_2
- bioconductor-safe=3.42.0=r43hdfd78af_0
- bioconductor-sparsearray=1.2.2=r43ha9d7317_2
- bioconductor-spia=2.54.0=r43hdfd78af_0
- bioconductor-summarizedexperiment=1.32.0=r43hdfd78af_0
- bioconductor-treeio=1.26.0=r43hdfd78af_1
- bioconductor-xvector=0.42.0=r43ha9d7317_2
- bioconductor-zlibbioc=1.48.0=r43ha9d7317_2
- biopython=1.81=py311h459d7ec_1
- blas=2.305=openblas
- blas-devel=3.11.0=5_h1ea3ea9_openblas
- brotlicffi=1.2.0.0=py311h7354ed3_0
- bwidget=1.10.1=h9eba36c_0
- bzip2=1.0.8=hda65f42_8
- c-ares=1.34.6=hd44998d_0
- ca-certificates=2026.1.4=hbd8a1cb_0
- cairo=1.18.4=h44eff21_0
- certifi=2026.01.04=py311h06a4308_0
- cffi=2.0.0=py311h4eded50_1
- charset-normalizer=3.4.4=py311h06a4308_0
- comm=0.2.3=py311h06a4308_0
- contourpy=1.3.1=py311hdb19cb5_0
- curl=8.18.0=h2d051e9_0
- cycler=0.12.1=py311h06a4308_0
- cyrus-sasl=2.1.28=h83b0a09_4
- dav1d=1.2.1=h5eee18b_0
- debugpy=1.8.16=py311hbdd6827_1
- decorator=5.2.1=py311h06a4308_0
- executing=2.2.1=py311h06a4308_0
- expat=2.7.3=h3385a95_0
- font-ttf-dejavu-sans-mono=2.37=hd3eb1b0_0
- font-ttf-inconsolata=2.001=hcb22688_0
- font-ttf-source-code-pro=2.030=hd3eb1b0_0
- font-ttf-ubuntu=0.83=h8b1ccd4_0
- fontconfig=2.15.0=h2c49b7f_0
- fonts-anaconda=1=h8fa9717_0
- fonts-conda-ecosystem=1=hd3eb1b0_0
- fonttools=4.61.0=py311h47b2149_0
- freetype=2.14.1=hf5b9546_0
- fribidi=1.0.16=h9fb5f84_0
- gcc_impl_linux-64=11.2.0=h1234567_1
- gcc_linux-64=11.2.0=h5c386dc_2
- gettext=0.21.0=hedfda30_2
- gfortran_impl_linux-64=11.2.0=h1234567_1
- gfortran_linux-64=11.2.0=hc2dff05_2
- glib=2.84.2=h6a678d5_0
- glib-tools=2.84.2=h6a678d5_0
- glpk=5.0=h445213a_0
- gmp=6.3.0=h6a678d5_0
- graphite2=1.3.14=h295c915_1
- gsl=2.7.1=h917eeb2_1
- gxx_impl_linux-64=11.2.0=h1234567_1
- gxx_linux-64=11.2.0=hc2dff05_2
- harfbuzz=10.2.0=hdfddeaa_1
- icu=73.1=h6a678d5_0
- idna=3.11=py311h06a4308_0
- ipykernel=6.31.0=py311h7040dfc_0
- ipython=9.7.0=py311h06a4308_0
- ipython_pygments_lexers=1.1.1=py311h06a4308_0
- jansson=2.14=h5eee18b_1
- jedi=0.19.2=py311h06a4308_0
- joblib=1.5.3=py311h06a4308_0
- jpeg=9f=h5ce9db8_0
- jupyter_client=8.8.0=py311h06a4308_0
- jupyter_core=5.9.1=py311h06a4308_0
- kernel-headers_linux-64=4.18.0=h3108a97_1
- kiwisolver=1.4.9=py311h24d9097_0
- krb5=1.21.3=h8a1dbc1_1
- lcms2=2.17=heab6991_0
- ld_impl_linux-64=2.40=h12ee557_0
- lerc=4.0.0=h6a678d5_0
- libabseil=20250127.0=cxx17_h6a678d5_0
- libavif=1.3.0=h3539ee5_0
- libblas=3.11.0=5_h4a7cf45_openblas
- libbrotlicommon=1.2.0=h32cd6e7_0
- libbrotlidec=1.2.0=ha2c5f68_0
- libbrotlienc=1.2.0=h2e96acb_0
- libcblas=3.11.0=5_h0358290_openblas
- libcups=2.4.15=hbe4054b_0
- libcurl=8.18.0=h3506a8c_0
- libdeflate=1.22=h5eee18b_0
- libdrm=2.4.124=h5eee18b_0
- libedit=3.1.20230828=h5eee18b_0
- libegl=1.7.0=h5eee18b_2
- libev=4.33=h7f8727e_1
- libevent=2.1.12=hdbd6064_1
- libexpat=2.7.3=hecca717_0
- libffi=3.4.4=h6a678d5_1
- libgcc=15.2.0=he0feb66_16
- libgcc-devel_linux-64=11.2.0=h1234567_1
- libgcc-ng=15.2.0=h69a702a_16
- libgfortran-ng=11.2.0=h00389a5_1
- libgfortran5=11.2.0=h1234567_1
- libgl=1.7.0=h5eee18b_2
- libglib=2.84.2=h37c7471_0
- libglvnd=1.7.0=h5eee18b_2
- libglx=1.7.0=h5eee18b_2
- libgomp=15.2.0=he0feb66_16
- libiconv=1.18=h3b78370_2
- libidn2=2.3.8=hf80d704_0
- libkrb5=1.22.1=h6d2bf13_0
- liblapack=3.11.0=5_h47877c9_openblas
- liblapacke=3.11.0=5_h6ae95b6_openblas
- libllvm15=15.0.7=he89c38a_4
- liblzma=5.8.2=hb03c661_0
- liblzma-devel=5.8.2=hb03c661_0
- libnghttp2=1.67.1=h697f920_0
- libnsl=2.0.1=hb9d3cd8_1
- libopenblas=0.3.30=h46f56fc_0
- libopenjpeg=2.5.4=hee96239_1
- libpciaccess=0.18=h5eee18b_0
- libpng=1.6.54=hee55ce4_0
- libpq=17.6=h5ca1609_1
- libprotobuf=5.29.3=h3cdef7c_1
- libsanitizer=15.2.0=h56912e6_7
- libsodium=1.0.20=heac8642_0
- libssh2=1.11.1=h251f7ec_0
- libstdcxx=15.2.0=h934c35e_16
- libstdcxx-devel_linux-64=11.2.0=h1234567_1
- libstdcxx-ng=15.2.0=hdf11a46_16
- libtiff=4.7.1=h029b1ac_0
- libunistring=1.3=hb25bd0a_0
- libuuid=1.41.5=h5eee18b_0
- libwebp-base=1.6.0=hb7bb969_0
- libxcb=1.17.0=h9b100fa_0
- libxcrypt=4.4.36=hd590300_1
- libxkbcommon=1.9.1=h69220b7_0
- libxml2=2.13.9=h2c43086_0
- lmdb=0.9.31=hb25bd0a_0
- lz4-c=1.9.4=h6a678d5_1
- make=4.2.1=h1bed415_1
- matplotlib=3.7.1=py311h06a4308_1
- matplotlib-base=3.7.1=py311ha02d727_1
- matplotlib-inline=0.2.1=py311h06a4308_0
- mesalib=25.1.5=h31e3550_0
- mysql=8.4.0=h721767e_2
- ncurses=6.5=h2d0b736_3
- nest-asyncio=1.6.0=py311h06a4308_0
- networkx=3.1=py311h06a4308_0
- nomkl=3.0=0
- numpy=1.24.3=py311hc213724_2
- numpy-base=1.24.3=py311hf387b04_2
- obonet=1.0.0=pyh7cba7a3_0
- openblas=0.3.30=h5426c36_0
- openblas-devel=0.3.30=h557178c_0
- openldap=2.6.10=he9288cc_1
- openssl=3.6.1=h35e630c_1
- packaging=26.0=pyhcf101f3_0
- pandas=2.0.1=py311h320fe9a_1
- pandoc=3.8=h06a4308_0
- pango=1.50.7=h668f713_2
- parso=0.8.5=py311h06a4308_0
- patsy=1.0.2=py311h06a4308_0
- pcre=8.45=h295c915_0
- pcre2=10.42=hebb0a14_1
- pexpect=4.9.0=py311h06a4308_1
- pillow=12.0.0=py311h3b88751_1
- pip=26.0=pyh8b19718_0
- pixman=0.46.4=h7934f7d_0
- platformdirs=4.5.0=py311h06a4308_0
- pooch=1.8.2=py311h06a4308_0
- prompt-toolkit=3.0.52=py311h06a4308_1
- prompt_toolkit=3.0.52=hd3eb1b0_1
- psutil=7.0.0=py311hee96239_1
- pthread-stubs=0.3=h0ce48e5_1
- ptyprocess=0.7.0=pyhd3eb1b0_3
- pure_eval=0.2.3=py311h06a4308_0
- pycparser=2.23=py311h06a4308_0
- pygments=2.19.2=py311h06a4308_0
- pyparsing=3.2.5=py311h06a4308_0
- pyqt=6.7.1=py311h8dad735_2
- pyqt6-sip=13.9.1=py311h6ce4db3_2
- pysocks=1.7.1=py311h06a4308_1
- python=3.11.14=h6fa692b_0
- python-dateutil=2.9.0post0=py311h06a4308_2
- python-tzdata=2025.3=pyhd3eb1b0_0
- python_abi=3.11=3_cp311
- pytz=2025.2=py311h06a4308_0
- pyyaml=6.0.3=py311h591646f_0
- pyzmq=27.1.0=py311hcf8288c_1
- qtbase=6.7.3=h10a5587_3
- qtdeclarative=6.7.3=h7934f7d_1
- qtsvg=6.7.3=he4bddd1_1
- qttools=6.7.3=h5a8de97_1
- qtwebchannel=6.7.3=h7934f7d_1
- qtwebsockets=6.7.3=h7934f7d_1
- r=4.3.1=r43_0
- r-abind=1.4_5=r43h142f84f_0
- r-ape=5.7_1=r43h884c59f_0
- r-aplot=0.2.2=r43h6115d3f_0
- r-ashr=2.2_63=r43h884c59f_0
- r-askpass=1.2.0=r43h76d94ec_0
- r-assertthat=0.2.1=r43h6115d3f_0
- r-base=4.3.1=h8399a1e_1
- r-base64enc=0.1_3=r43h76d94ec_4
- r-bbmle=1.0.25=r43h142f84f_0
- r-bdsmatrix=1.3_6=r43h76d94ec_0
- r-bh=1.81.0_1=r43h6115d3f_0
- r-biocmanager=1.30.26=r43hc72bb7e_0
- r-bit=4.0.5=r43h76d94ec_0
- r-bit64=4.0.5=r43h76d94ec_0
- r-bitops=1.0_7=r43h76d94ec_0
- r-blob=1.2.4=r43h6115d3f_0
- r-boot=1.3_28.1=r43h6115d3f_0
- r-bslib=0.5.1=r43h6115d3f_0
- r-cachem=1.0.8=r43h76d94ec_0
- r-catools=1.18.2=r43h884c59f_0
- r-class=7.3_22=r43h76d94ec_0
- r-cli=3.6.1=r43h884c59f_0
- r-cluster=2.1.4=r43h640688f_0
- r-coda=0.19_4=r43h6115d3f_0
- r-codetools=0.2_19=r43h6115d3f_0
- r-colorspace=2.1_0=r43h76d94ec_0
- r-commonmark=1.9.0=r43h76d94ec_0
- r-cowplot=1.1.1=r43h6115d3f_0
- r-cpp11=0.4.6=r43h6115d3f_0
- r-crayon=1.5.2=r43h6115d3f_0
- r-crosstalk=1.2.0=r43h6115d3f_0
- r-curl=5.1.0=r43h76d94ec_0
- r-data.table=1.14.8=r43h76d94ec_0
- r-dbi=1.1.3=r43h6115d3f_0
- r-dbplyr=2.3.4=r43h6115d3f_0
- r-dichromat=2.0_0.1=r43h6115d3f_0
- r-digest=0.6.33=r43h884c59f_0
- r-downloader=0.4=r43h6115d3f_0
- r-dplyr=1.1.3=r43h884c59f_0
- r-dt=0.30=r43h6115d3f_0
- r-ellipsis=0.3.2=r43h76d94ec_0
- r-emdbook=1.3.13=r43h142f84f_0
- r-etrunct=0.1=r43h142f84f_0
- r-evaluate=0.22=r43h6115d3f_0
- r-fansi=1.0.5=r43h76d94ec_0
- r-farver=2.1.1=r43h884c59f_0
- r-fastmap=1.1.1=r43h884c59f_0
- r-fastmatch=1.1_4=r43h76d94ec_0
- r-filelock=1.0.2=r43h76d94ec_0
- r-fontawesome=0.5.2=r43h6115d3f_0
- r-foreign=0.8_85=r43h76d94ec_0
- r-formatr=1.14=r43h6115d3f_0
- r-fs=1.6.3=r43h884c59f_0
- r-futile.logger=1.4.3=r43h6115d3f_0
- r-futile.options=1.0.1=r43h142f84f_0
- r-generics=0.1.3=r43h142f84f_0
- r-getopt=1.20.4=r43h6115d3f_0
- r-ggforce=0.4.1=r43h884c59f_0
- r-ggfun=0.1.3=r43h6115d3f_0
- r-ggnewscale=0.4.9=r43h6115d3f_0
- r-ggplot2=3.4.4=r43h6115d3f_0
- r-ggplotify=0.1.2=r43h6115d3f_0
- r-ggraph=2.1.0=r43h884c59f_0
- r-ggrepel=0.9.4=r43h884c59f_0
- r-glue=1.6.2=r43h76d94ec_0
- r-gplots=3.1.3=r43h6115d3f_0
- r-graphlayouts=1.0.1=r43h884c59f_0
- r-gridextra=2.3=r43h6115d3f_0
- r-gridgraphics=0.5_1=r43h142f84f_0
- r-gson=0.1.0=r43h6115d3f_0
- r-gtable=0.3.4=r43h6115d3f_0
- r-gtools=3.9.4=r43h76d94ec_0
- r-here=1.0.1=r43h142f84f_0
- r-highr=0.10=r43h6115d3f_0
- r-htmltools=0.5.6.1=r43h76d94ec_0
- r-htmlwidgets=1.6.2=r43h6115d3f_0
- r-httpuv=1.6.11=r43h884c59f_0
- r-httr=1.4.7=r43h6115d3f_0
- r-hwriter=1.3.2.1=r43h142f84f_0
- r-igraph=1.5.1=r43hb5eb8f6_0
- r-invgamma=1.1=r43h142f84f_0
- r-irlba=2.3.5.1=r43h76d94ec_0
- r-isoband=0.2.7=r43h884c59f_0
- r-jquerylib=0.1.4=r43h6115d3f_0
- r-jsonlite=1.8.7=r43h76d94ec_0
- r-kernsmooth=2.23_22=r43h640688f_0
- r-knitr=1.44=r43h6115d3f_0
- r-labeling=0.4.3=r43h6115d3f_0
- r-lambda.r=1.2.4=r43h142f84f_0
- r-later=1.3.1=r43h884c59f_0
- r-lattice=0.22_5=r43h76d94ec_0
- r-lazyeval=0.2.2=r43h76d94ec_0
- r-lifecycle=1.0.3=r43h142f84f_0
- r-locfit=1.5_9.8=r43h76d94ec_0
- r-magrittr=2.0.3=r43h76d94ec_0
- r-mass=7.3_60=r43h76d94ec_0
- r-matrix=1.6_1.1=r43h76d94ec_0
- r-matrixstats=1.0.0=r43h76d94ec_0
- r-memoise=2.0.1=r43h6115d3f_0
- r-mgcv=1.9_0=r43h76d94ec_0
- r-mime=0.12=r43h76d94ec_0
- r-mixsqp=0.3_48=r43h884c59f_0
- r-munsell=0.5.0=r43h6115d3f_0
- r-mvtnorm=1.2_3=r43h640688f_0
- r-nlme=3.1_163=r43h640688f_0
- r-nnet=7.3_19=r43h76d94ec_0
- r-numderiv=2016.8_1.1=r43h6115d3f_0
- r-openssl=2.1.1=r43h76d94ec_0
- r-optparse=1.7.3=r43h142f84f_0
- r-patchwork=1.1.3=r43h6115d3f_0
- r-pillar=1.9.0=r43h6115d3f_0
- r-pkgconfig=2.0.3=r43h6115d3f_0
- r-plogr=0.2.0=r43h6115d3f_0
- r-plyr=1.8.9=r43h884c59f_0
- r-png=0.1_8=r43h76d94ec_0
- r-polyclip=1.10_6=r43h884c59f_0
- r-prettyunits=1.2.0=r43h142f84f_0
- r-promises=1.2.1=r43h884c59f_0
- r-purrr=1.0.2=r43h76d94ec_0
- r-r6=2.5.1=r43h6115d3f_0
- r-rappdirs=0.3.3=r43h76d94ec_0
- r-rcolorbrewer=1.1_3=r43h6115d3f_1
- r-rcpp=1.0.11=r43h884c59f_0
- r-rcpparmadillo=0.12.6.4.0=r43h884c59f_0
- r-rcppeigen=0.3.3.9.3=r43h884c59f_0
- r-rcppnumerical=0.6_0=r43h884c59f_0
- r-rcpptoml=0.2.2=r43h884c59f_0
- r-rcurl=1.98_1.12=r43h76d94ec_0
- r-recommended=4.3.1=r43_0
- r-reshape2=1.4.4=r43h884c59f_0
- r-reticulate=1.34.0=py311r43h884c59f_0
- r-rlang=1.1.1=r43h884c59f_0
- r-rmarkdown=2.25=r43h6115d3f_0
- r-rpart=4.1.21=r43h76d94ec_0
- r-rprojroot=2.0.3=r43h6115d3f_0
- r-rsqlite=2.3.1=r43h884c59f_0
- r-sass=0.4.7=r43h884c59f_0
- r-scales=1.2.1=r43h6115d3f_0
- r-scatterpie=0.2.1=r43h6115d3f_0
- r-shadowtext=0.1.2=r43h6115d3f_0
- r-shiny=1.7.5.1=r43h6115d3f_0
- r-snow=0.4_4=r43h142f84f_0
- r-sourcetools=0.1.7_1=r43h884c59f_0
- r-sparsem=1.81=r43h640688f_0
- r-spatial=7.3_17=r43h76d94ec_0
- r-squarem=2021.1=r43h142f84f_0
- r-statmod=1.5.0=r43h640688f_0
- r-stringi=1.7.12=r43h884c59f_0
- r-stringr=1.5.0=r43h6115d3f_0
- r-survival=3.5_7=r43h76d94ec_0
- r-sys=3.4.2=r43h76d94ec_0
- r-systemfonts=1.0.5=r43h884c59f_0
- r-tibble=3.2.1=r43h76d94ec_0
- r-tidygraph=1.2.3=r43h884c59f_0
- r-tidyr=1.3.1=r43h0d4f4ea_1
- r-tidyselect=1.2.0=r43h6115d3f_0
- r-tidytree=0.4.5=r43h6115d3f_0
- r-tinytex=0.48=r43h142f84f_0
- r-truncnorm=1.0_9=r43h76d94ec_0
- r-tweenr=2.0.2=r43h884c59f_0
- r-utf8=1.2.4=r43h76d94ec_0
- r-vctrs=0.6.4=r43h884c59f_0
- r-viridis=0.6.4=r43h6115d3f_0
- r-viridislite=0.4.2=r43h6115d3f_0
- r-withr=2.5.1=r43h6115d3f_0
- r-xfun=0.40=r43h76d94ec_0
- r-xml=3.99_0.17=r43h76d94ec_0
- r-xtable=1.8_4=r43h6115d3f_0
- r-yaml=2.3.7=r43h76d94ec_0
- r-yulab.utils=0.1.0=r43h6115d3f_0
- readline=8.3=h853b02a_0
- requests=2.32.5=py311h06a4308_1
- scikit-learn=1.6.1=py311h6a678d5_0
- scikit-posthocs=0.11.4=pyhd8ed1ab_0
- scipy=1.10.1=py311h24aa872_1
- seaborn=0.13.2=py311h06a4308_3
- sed=4.9=hb25bd0a_0
- setuptools=80.10.2=pyh332efcf_0
- sip=6.10.0=py311h6a678d5_0
- six=1.17.0=py311h06a4308_0
- spirv-tools=2025.1=hdb19cb5_0
- sqlite=3.51.1=he0a8d7e_0
- stack_data=0.6.3=py311h06a4308_0
- statsmodels=0.14.6=py311h47b2149_0
- sysroot_linux-64=2.28=h3108a97_1
- threadpoolctl=3.5.0=py311h7040dfc_1
- tk=8.6.15=h54e0aa7_0
- tktable=2.10=hfce700a_2
- tomlkit=0.13.3=py311h06a4308_0
- tornado=6.5.4=py311h47b2149_0
- traitlets=5.14.3=py311h06a4308_0
- typing_extensions=4.15.0=py311h06a4308_0
- tzdata=2025c=hc9c84f9_1
- urllib3=2.6.3=py311h06a4308_0
- wcwidth=0.2.14=py311h06a4308_0
- wheel=0.46.3=pyhd8ed1ab_0
- xcb-util=0.4.1=h5eee18b_2
- xcb-util-cursor=0.1.5=h5eee18b_0
- xcb-util-image=0.4.0=h5eee18b_2
- xcb-util-keysyms=0.4.1=h5eee18b_0
- xcb-util-renderutil=0.3.10=h5eee18b_0
- xcb-util-wm=0.4.2=h5eee18b_0
- xkeyboard-config=2.44=h382ed1a_1
- xmltodict=1.0.2=py311h06a4308_0
- xorg-libice=1.1.2=h9b100fa_0
- xorg-libsm=1.2.6=h9b100fa_0
- xorg-libx11=1.8.12=h9b100fa_1
- xorg-libxau=1.0.12=h9b100fa_0
- xorg-libxdmcp=1.1.5=h9b100fa_0
- xorg-libxext=1.3.6=h9b100fa_0
- xorg-libxfixes=6.0.1=h9b100fa_0
- xorg-libxrandr=1.5.4=h9b100fa_0
- xorg-libxrender=0.9.12=h9b100fa_0
- xorg-libxshmfence=1.3.3=h9b100fa_0
- xorg-libxt=1.3.1=h9b100fa_0
- xorg-libxxf86vm=1.1.6=h9b100fa_0
- xorg-xorgproto=2024.1=h5eee18b_1
- xz=5.8.2=ha02ee65_0
- xz-gpl-tools=5.8.2=ha02ee65_0
- xz-tools=5.8.2=hb03c661_0
- yaml=0.2.5=h7b6447c_0
- yq=3.4.3=py311h06a4308_0
- zeromq=4.3.5=hb0a5e54_1
- zlib=1.2.13=hd233ad5_2
- zstd=1.5.6=hc292b87_0

